logging:
  level:
    org:
      springframework:
        web: INFO
  file: /var/www/gateway.log
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
spring:
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: test_api
          uri: http://192.168.4.144:8088/api/**
          predicates:
            - Path=/api/**
        - id: wcf_api
          uri: http://apicache200.517.dev:51707/User/**
          predicates:
            - Path=/User/**
#开启actuator管理api，后面要关闭
management:
  endpoints:
    web:
      exposure:
        include: "*"
