logging:
  level:
    org:
      springframework:
        web: INFO,ERROR
  file: /var/www/gateway.log
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
spring:
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: ping
          uri: http://${csp.sentinel.dashboard.server}/ping
          predicates:
            - Path=/ping
#开启actuator管理api，后面要关闭
management:
  endpoints:
    web:
      exposure:
        include: "*"
